// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHHRCGREnyGS5tb1aM9c1izuBKnGyKrQk',
    appId: '1:862199949919:web:42a085e5d6bda3a2b4c9ea',
    messagingSenderId: '862199949919',
    projectId: 'plugs-9ff92',
    authDomain: 'plugs-9ff92.firebaseapp.com',
    storageBucket: 'plugs-9ff92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwTfBLLVK3x3AOE_X9r3yz7cDM7R5el5c',
    appId: '1:862199949919:android:f89a38b75a82445db4c9ea',
    messagingSenderId: '862199949919',
    projectId: 'plugs-9ff92',
    storageBucket: 'plugs-9ff92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBza3CXzWvN7ESanqQGZZMoEF6kkg0y3Ok',
    appId: '1:862199949919:ios:3c19b325c0e98468b4c9ea',
    messagingSenderId: '862199949919',
    projectId: 'plugs-9ff92',
    storageBucket: 'plugs-9ff92.firebasestorage.app',
    iosClientId: '862199949919-nobc2sk8bgamjigpf5c7h567et5i01ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBza3CXzWvN7ESanqQGZZMoEF6kkg0y3Ok',
    appId: '1:862199949919:ios:3c19b325c0e98468b4c9ea',
    messagingSenderId: '862199949919',
    projectId: 'plugs-9ff92',
    storageBucket: 'plugs-9ff92.firebasestorage.app',
    iosClientId: '862199949919-nobc2sk8bgamjigpf5c7h567et5i01ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHHRCGREnyGS5tb1aM9c1izuBKnGyKrQk',
    appId: '1:862199949919:web:869526b58f57c6a9b4c9ea',
    messagingSenderId: '862199949919',
    projectId: 'plugs-9ff92',
    authDomain: 'plugs-9ff92.firebaseapp.com',
    storageBucket: 'plugs-9ff92.firebasestorage.app',
  );
}
